
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.195.129:3306/guli_pms
    username: root
    password: root
server:
  port: 8081
mybatis-plus:
  mapper-locations: classpath:mapper/pms/*.xml
  global-config:
    db-config:
      id-type: auto